apiVersion: v1
kind: Secret
metadata:
  name: collectorset-controller
type: Opaque
data:
  accessID: {{ required "A valid .Values.global.accessID entry is required!" .Values.global.accessID | b64enc }}
  accessKey: {{ required "A valid .Values.global.accessKey entry is required!" .Values.global.accessKey | b64enc }}
  account: {{ required "A valid .Values.global.account entry is required!" .Values.global.account | b64enc }}
  etcdDiscoveryToken: {{ default "" .Values.etcdDiscoveryToken | b64enc | quote }}
