---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collectorset-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
