replicaCount: 1
argus:
imageRepository: logicmonitor/argus
imageTag: 0.1.0-alpha.3
imagePullPolicy: Always
collectorSize: small
collectorVersion: 24200
disableAlerting: false
deleteDevices: false
debug: false
