replicaCount: 1
argus:
imageRepository: logicmonitor/argus
imageTag: latest
imagePullPolicy: Always
collectorSize: small
disableAlerting: false
deleteDevices: false
debug: false
enableRBAC: true
useEACollector: false
nodeSelector: {}
