replicaCount: 1
argus:
imageRepository: logicmonitor/argus
imageTag: latest
imagePullPolicy: Always
collectorSize: small
collectorVersion: 24200
disableAlerting: false
deleteDevices: false
debug: false
enableRBAC: true
