{{- if .Values.enableRBAC -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: argus
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - containers
    - nodes
    - services
    - namespaces
    - componentstatuses
  verbs:
    - list
    - get
    - watch
    - update
- nonResourceURLs:
    - /
    - /healthz
    - /healthz/*
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: argus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argus
subjects:
- kind: ServiceAccount
  name: argus
  namespace: {{ .Release.Namespace }}
{{- end -}}
