kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "fluentd.name" . }}
  labels:
    {{- include "fluentd.selectorLabels" . | nindent 4 }}
data:
  fluent.conf: |
    @include kubernetes.conf

    <system>
      log_level warn
    </system>

    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
      </match>
    </label>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby
      <record>
        message ${record["log"]}
        timestamp ${record["time"]}
      </record>
    </filter>

    <match kubernetes.var.log.containers.{{ include "fluentd.fullname" . }}**>
     @type null
    </match>

    <match kubernetes.**>
      @type lm
      company_name {{ .Values.lm_company_name }}
      resource_mapping {"kubernetes.pod_name": "auto.name"}
      access_id {{ .Values.lm_access_id }}
      access_key {{ .Values.lm_access_key }}
      debug false
      compression gzip
      <buffer>
        @type memory
        flush_interval 1s
        chunk_limit_size 5m
      </buffer> 
    </match>
  kubernetes.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag "#{ENV['FLUENT_CONTAINER_TAIL_TAG'] || 'kubernetes.*'}"
      exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
      <parse>
        @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
        keep_time_key true
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
  
    
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
      skip_labels "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_LABELS'] || 'false'}"
      skip_container_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_CONTAINER_METADATA'] || 'false'}"
      skip_master_url "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_MASTER_URL'] || 'false'}"
      skip_namespace_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_NAMESPACE_METADATA'] || 'false'}"
    </filter>
